title: Blog Bibliotheks- und Archivinformatik
author: Christina Clerici
description: Dies ist mein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS 2021

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
